export type ActionType = {
	type: string;
	/* eslint-disable @typescript-eslint/no-explicit-any */
	payload: any;
};

//USER DASHBOARD ACTIONS
export const USER_LOGIN_SUCCESSFULL = "USER_LOGIN_SUCCESSFULL";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";
export const USER_REGISTRATION_SUCCESSFULL = "USER_REGISTRATION_SUCCESSFULL";
export const USER_REGISTRATION_FAILURE = "USER_REGISTRATION_FAILURE";
export const USER_LOADING = "USER_LOADING";
export const USER_LOGOUT_SUCCESSFUL = "USER_LOGOUT_SUCCESSFUL";
export const USER_LOGOUT_FAILURE = "USER_LOGOUT_FAILURE";
export const PLAYBACK_PAUSE_SUCCESSFULL = "PLAYBACK_PAUSE_SUCCESSFULL";
export const PLAYBACK_PAUSE_FAILURE = "PLAYBACK_PAUSE_FAILURE";
export const PLAYBACK_RESUME_SUCCESSFULL = "PLAYBACK_RESUME_SUCCESSFULL";
export const PLAYBACK_RESUME_FAILURE = "PLAYBACK_RESUME_FAILURE";
export const PLAYBACK_SKIP_NEXT_SUCCESSFULL = "PLAYBACK_SKIP_NEXT_SUCCESSFULL";
export const PLAYBACK_SKIP_NEXT_FAILURE = "PLAYBACK_SKIP_NEXT_FAILURE";
export const PLAYBACK_SKIP_PREVIOUS_SUCCESSFULL =
	"PLAYBACK_SKIP_PREVIOUS_SUCCESSFULL";
export const PLAYBACK_SKIP_PREVIOUS_FAILURE = "PLAYBACK_SKIP_PREVIOUS_FAILURE";
export const PLAYBACK_STATE_UPDATE = "PLAYBACK_STATE_UPDATE";
export const ACTION_IN_PROCESS = "ACTION_IN_PROCESS";
export const LOADING = "LOADING";
export const RESTAURANT_UPDATE_SUCCESSFUL = "RESTAURANT_UPDATE_SUCCESSFUL";
export const RESTAURANT_UPDATE_FAILURE = "RESTAURANT_UPDATE_FAILURE";
export const CLEAR_RESTAURANT_NAME_INPUT_ERROR = "CLEAR_RESTAURANT_NAME_INPUT_ERROR";
export const DISABLE_INPUT_BUTTON = "DISABLE_INPUT_BUTTON";

//CUSTOMER DASHBOARD ACTIONS
export const CUSTOMER_DATA_LOAD_SUCCESSFULL = "CUSTOMER_DATA_LOAD_SUCCESSFULL";
export const CUSTOMER_DATA_LOAD_FAILURE = "CUSTOMER_DATA_LOAD_FAILURE";
export const SET_USER_RESTAURANT = "LOAD_USER_RESTAURANT";


//SEARCH ACTIONS
export const CLEAR_SEARCH_ERROR =  "CLEAR_SEARCH_ERROR";
export const SEARCH_SUCCESSFULL = "SEARCH_SUCCESSFULL";
export const SEARCH_FAILURE = "SEARCH_FAILURE";
export const DISABLE_SEARCH_BUTTON = "DISABLE_SEARCH_BUTTON";

//PAYMENT ACTIONS
export const PAYMENT_REQUEST_LOADING = "PAYMENT_REQUEST_LOADING";
export const PAYMENT_REQUEST_SUCCESS = "PAYMENT_REQUEST_SUCCESS";
export const PAYMENT_REQUEST_FAILURE = "PAYMENT_REQUEST_FAILURE";
